### ISSUE TITLE
Noticed a typo in a Facebook ad for FAC Nazareth

### ISSUE THREAD

**Issue by JWLD** [foundersandcoders/nazareth-marketing#14]
You can see it here. I would fix it myself but not sure how / what the login details are!

![typo](https://cloud.githubusercontent.com/assets/23030305/24894983/77df1398-1e96-11e7-9ad3-1ef01922ff81.png)

**Comment by rebeccaradding** [comment]
Closing, as Serene Afifi has fixed this issue.
